//! Embed the committed web UI bundle (`ui/dist`) into the crate (ADR-0078).
//!
//! **This build script never runs Node and never touches the network**, and it
//! must stay that way: `cargo install opys`, docs.rs and the nix sandbox all
//! build with no Node and no network. `ui/dist` is a *committed* build product,
//! regenerated by the `ui-build` devShell command and drift-checked in CI. If it
//! is missing, the build fails with instructions — never by fetching, and never
//! by silently producing a server that serves a blank page.
//!
//! The output is `$OUT_DIR/assets.rs`: one static table of
//! `(url path, content type, bytes)` with an `include_bytes!` per file, anchored
//! at `CARGO_MANIFEST_DIR` so it also resolves when cargo verifies a packaged
//! tarball in a temp directory.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("set by cargo"));
    let dist = manifest_dir.join("ui/dist");

    // Re-run when files appear or disappear. Per-file directives follow, which
    // is what catches an edit in place: a directory watch only sees its own
    // mtime change, so a rebuild that reuses a filename would go unnoticed.
    println!("cargo::rerun-if-changed=ui/dist");
    println!("cargo::rerun-if-changed=build.rs");

    let mut files = Vec::new();
    if let Err(problem) = collect(&dist, &dist, &mut files) {
        fail(&format!("cannot read {}: {problem}", dist.display()));
        return;
    }
    if files.is_empty() {
        fail(&format!("{} is empty or missing", dist.display()));
        return;
    }
    // Directory order is filesystem-dependent; sorting keeps the generated file
    // byte-stable so an unrelated rebuild does not churn.
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs from ui/dist — do not edit.\n\
         /// Every file of the committed bundle: (path below `ui/dist`, content type, bytes).\n\
         pub static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for url in &files {
        println!("cargo::rerun-if-changed=ui/dist/{url}");
        let _ = writeln!(
            out,
            "    ({url:?}, {ctype:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/ui/dist/{url}\"))),",
            ctype = content_type(url),
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("set by cargo")).join("assets.rs");
    if let Err(problem) = std::fs::write(&dest, out) {
        panic!("writing {}: {problem}", dest.display());
    }
}

/// Report a missing bundle and stop, without compiling the crate.
///
/// `cargo::error` plus a plain return, rather than `process::exit`: cargo prints
/// these lines as errors and refuses to build the crate, and exiting non-zero
/// would additionally dump the raw directives and a "failed to run custom build
/// command" wrapper around a message that is already clear.
fn fail(detail: &str) {
    println!("cargo::error=the opys-server web UI bundle is not built: {detail}");
    println!(
        "cargo::error=run `ui-build` in the devShell (or `npm ci && npm run build` in \
         opys-server/ui) and commit ui/dist"
    );
}

/// Every file below `dir`, as a `/`-separated path relative to `root`.
fn collect(root: &Path, dir: &Path, into: &mut Vec<String>) -> std::io::Result<()> {
    if !dir.exists() {
        return Ok(());
    }
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_dir() {
            collect(root, &path, into)?;
            continue;
        }
        let relative = path.strip_prefix(root).unwrap_or(&path);
        let url: Vec<String> = relative
            .components()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .collect();
        into.push(url.join("/"));
    }
    Ok(())
}

/// The `Content-Type` for a bundled file.
///
/// Kept here rather than pulled from a mime crate: the bundle contains a handful
/// of extensions we produce ourselves, and a wrong guess is a blank page.
fn content_type(url: &str) -> &'static str {
    let extension = url.rsplit_once('.').map(|(_, e)| e).unwrap_or_default();
    match extension {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "gif" => "image/gif",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "txt" => "text/plain; charset=utf-8",
        "wasm" => "application/wasm",
        _ => "application/octet-stream",
    }
}
