#!/usr/bin/env node
// Render the web UI's PNG icons from their SVG sources (FEAT-0127).
//
//   node scripts/ui-icons.cjs
//
// The SVGs are the source: opys-server/ui/public/icon.svg (served as is, and
// the tab favicon) and opys-server/ui/icons/icon-maskable.svg. The PNGs in
// ui/public/ are committed outputs, regenerated by hand when a source changes
// — not part of `ui-build`, because rendering needs a browser and the bundle
// build must not. Uses Playwright's Chromium (PLAYWRIGHT_BROWSERS_PATH or a
// global `playwright` install).
const fs = require('fs');
const path = require('path');

let chromium;
try {
  ({ chromium } = require('playwright'));
} catch {
  ({ chromium } = require(path.join(path.dirname(process.execPath), '../lib/node_modules/playwright')));
}

const ui = path.join(__dirname, '../opys-server/ui');
const sources = {
  any: path.join(ui, 'public/icon.svg'),
  maskable: path.join(ui, 'icons/icon-maskable.svg'),
};
const outputs = [
  ['icon-192.png', 'any', 192],
  ['icon-maskable-512.png', 'maskable', 512],
  // iOS draws its own rounded corners, so it gets the full-bleed square.
  ['apple-touch-icon.png', 'maskable', 180],
];

(async () => {
  const browser = await chromium.launch();
  for (const [name, source, size] of outputs) {
    const svg = fs.readFileSync(sources[source], 'utf8').replace('<svg ', `<svg width="${size}" height="${size}" `);
    const page = await browser.newPage({ viewport: { width: size, height: size } });
    await page.setContent(`<html><body style="margin:0">${svg}</body></html>`);
    await page.screenshot({ path: path.join(ui, 'public', name), omitBackground: true });
    console.log(`${name} ← ${path.relative(ui, sources[source])} at ${size}px`);
  }
  await browser.close();
})();
